// Copyright (C) 2026 Jonathan Cilley <jonathan.cilley@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileText, AlertTriangle, Printer, Shield, ShieldAlert, Download, Info } from "lucide-react";

interface AuditQuestion {
  id: string;
  category: "Security" | "Fairness" | "Resilience" | "Legal";
  question: string;
  points: number;
  gapText: string;
  vendorQuestion: string;
}

export default function VendorAuditor() {
  const auditQuestions: AuditQuestion[] = [
    {
      id: "soc_2",
      category: "Security",
      question: "Audit Credentials: Does the vendor hold a current, independent SOC 2 Type II compliance audit report?",
      points: 20,
      gapText: "Vendor has no SOC 2 Type II audit. Information security controls, employee accesses, and backup protocols are completely unverified by third parties.",
      vendorQuestion: "Can you provide your latest SOC 2 Type II audit report, or specify when your next independent audit review is scheduled?"
    },
    {
      id: "data_isolation",
      category: "Security",
      question: "Data Isolation: Does the agreement legally prohibit the vendor from using your inputs/prompts to train future model weights?",
      points: 20,
      gapText: "Data leakage risk. Member profiles, chats, and credit union prompts may be absorbed into public LLM training sets and exposed.",
      vendorQuestion: "Does your standard SaaS agreement include a zero-data-retention policy for API inputs, and does it explicitly prohibit model training on our prompt data?"
    },
    {
      id: "bias_audit",
      category: "Fairness",
      question: "Bias Assessments: Has the vendor completed an independent algorithmic fairness/bias audit for credit discrimination?",
      points: 20,
      gapText: "Fair Lending threat. The system's decisions have not been mathematically checked for bias against protected demographic classes under ECOA.",
      vendorQuestion: "Can you provide the documentation or independent audit report verifying that your model's scoring factors are free of systemic bias?"
    },
    {
      id: "explainability",
      category: "Fairness",
      question: "Explainable Criteria: Does the model supply transparent credit scoring variables instead of opaque black-box recommendations?",
      points: 15,
      gapText: "Audit trail gap. If the model flags exceptions or recommends credit denials, staff cannot explain the underlying variables to regulators or members.",
      vendorQuestion: "How does the system calculate credit recommendations, and what explainability frameworks (e.g. SHAP or LIME values) are exposed in the audit logs?"
    },
    {
      id: "encryption",
      category: "Security",
      question: "Data Encryption: Are raw prompts and observation data encrypted both in transit (TLS 1.3) and at rest (AES-256)?",
      points: 15,
      gapText: "Transmission threat. Member communications and metadata are vulnerable to packet eavesdropping or database theft.",
      vendorQuestion: "Can you verify that TLS 1.3 is enforced for all API traffic, and describe how encryption keys are managed for data at rest?"
    },
    {
      id: "sla_agreements",
      category: "Resilience",
      question: "SLA Guarantees: Is there an SLA agreement guaranteeing at least 99.9% availability with monetary service credits for downtime?",
      points: 10,
      gapText: "Operational exposure. There is no financial protection or structural guarantee if the vendor experiences a system outage during branch hours.",
      vendorQuestion: "What is your target uptime SLA, and what credits are issued if monthly uptime drops below 99.9%?"
    },
    {
      id: "data_extract",
      category: "Legal",
      question: "Data Extraction: Can the credit union extract 100% of its data and verify complete deletion upon contract termination?",
      points: 15,
      gapText: "Vendor lock-in risk. If the credit union ends the partnership, the vendor may retain member transaction traces indefinitely in their databases.",
      vendorQuestion: "Upon termination of services, how do we retrieve our structured databases, and what certificate of deletion is issued to verify records removal?"
    },
    {
      id: "indemnification",
      category: "Legal",
      question: "Copyright Indemnity: Does the contract fully indemnify the credit union against copyright, intellectual property, or accuracy lawsuits?",
      points: 20,
      gapText: "Uncapped legal liability. The credit union bears full legal and financial responsibility if the AI model outputs copyrighted text or hallucinates false advice.",
      vendorQuestion: "Does your company assume full intellectual property and accuracy indemnification for outputs generated by the agent in our workflows?"
    },
    {
      id: "training_lineage",
      category: "Fairness",
      question: "Training Lineage: Does the vendor document training sets and screen for toxic, copyrighted, or demographically imbalanced records?",
      points: 15,
      gapText: "Data lineage exposure. Training data holds unverified copyright boundaries and potential historical redlining bias that will infect downstream models.",
      vendorQuestion: "Can you provide the provenance report for your training data and document what fairness algorithms were run to screen for historical lending bias?"
    },
    {
      id: "model_drift",
      category: "Resilience",
      question: "Model Drift Audits: Does the vendor monitor model decay over time and supply quarterly performance validation audits?",
      points: 15,
      gapText: "Model decay risk. The model's reasoning is unchecked for drift as real-world interest rates, policies, and member loan profiles change.",
      vendorQuestion: "Do you supply regular validation audits showing that the model's accuracy, precision, and drift metrics remain within compliance thresholds?"
    },
    {
      id: "llm_vulnerability",
      category: "Security",
      question: "Vulnerability Shielding: Does the architecture defend against prompt injections, data poisoning, and model extraction (OWASP LLM Top 10)?",
      points: 15,
      gapText: "Prompt exploit vulnerability. The vendor lacks firewall guards, making them vulnerable to indirect prompt injections or system jailbreaks.",
      vendorQuestion: "How do you shield your model API from indirect prompt injections, and do you conduct regular penetration testing for LLM exploits?"
    },
    {
      id: "pii_scrubbing",
      category: "Security",
      question: "PII Client Scrubbing: Does the system automatically scrub or mask SSNs, names, and account numbers *before* sending data to the cloud?",
      points: 15,
      gapText: "Data protection breach. Member PII is transmitted in raw text to third-party vendor servers, violating Gramm-Leach-Bliley Act guidelines.",
      vendorQuestion: "What client-side scrubbing filters are active, and can you verify that raw member SSNs are masked before hitting your database API?"
    },
    {
      id: "model_failover",
      category: "Resilience",
      question: "Model Redundancy: Is there an automated failover LLM to preserve branch continuity if the primary API provider suffers an outage?",
      points: 10,
      gapText: "Outage vulnerability. A primary API provider outage (e.g. OpenAI) will crash the vendor's service, disrupting member service at the branch.",
      vendorQuestion: "Do you maintain a secondary failover architecture (e.g. self-hosted Llama or alternative provider) to guarantee business continuity?"
    },
    {
      id: "system_logs",
      category: "Security",
      question: "Structured Logs: Does the vendor log system parameters (temperatures, prompt templates, instructions) to verify policy adherence?",
      points: 10,
      gapText: "Oversight log gap. Administrators cannot trace whether the model's backend system prompts or temperature settings were changed by the vendor.",
      vendorQuestion: "Are system instruction parameters, temperature values, and model versions included in the read-only audit log outputs?"
    }
  ];

  const [vendorName, setVendorName] = useState("CreditLend AI Inc.");
  const [selectedAnswers, setSelectedAnswers] = useState<Record<string, boolean>>({
    soc_2: true,
    data_isolation: true,
    bias_audit: false,
    explainability: false,
    encryption: true,
    sla_agreements: true,
    data_extract: false,
    indemnification: false,
    training_lineage: false,
    model_drift: false,
    llm_vulnerability: true,
    pii_scrubbing: false,
    model_failover: true,
    system_logs: false
  });

  const [showBrief, setShowBrief] = useState(false);
  const [showPDFTip, setShowPDFTip] = useState(false);

  const handleExportPDF = () => {
    setShowPDFTip(true);
    setTimeout(() => {
      window.print();
    }, 1000);
    setTimeout(() => {
      setShowPDFTip(false);
    }, 4500);
  };

  const toggleAnswer = (id: string) => {
    setSelectedAnswers(prev => ({ ...prev, [id]: !prev[id] }));
    setShowBrief(false);
  };

  // Compile Grade
  const compileAudit = () => {
    let earnedPoints = 0;
    let maxPoints = 0;

    auditQuestions.forEach((q) => {
      maxPoints += q.points;
      if (selectedAnswers[q.id]) {
        earnedPoints += q.points;
      }
    });

    const scorePercentage = Math.round((earnedPoints / maxPoints) * 100);

    let grade: "A" | "B" | "C" | "F" = "F";
    let riskLevel = "Critical";
    let color = "var(--danger)";
    let bg = "var(--danger-glow)";

    if (scorePercentage >= 90) {
      grade = "A";
      riskLevel = "Low Risk";
      color = "var(--success)";
      bg = "var(--success-glow)";
    } else if (scorePercentage >= 75) {
      grade = "B";
      riskLevel = "Moderate Risk";
      color = "var(--primary)";
      bg = "var(--primary-glow)";
    } else if (scorePercentage >= 60) {
      grade = "C";
      riskLevel = "High Risk";
      color = "var(--warning)";
      bg = "var(--warning-glow)";
    }

    // Filter gaps and vendor questions
    const gaps = auditQuestions.filter((q) => !selectedAnswers[q.id]);

    return { scorePercentage, grade, riskLevel, color, bg, gaps };
  };

  const report = compileAudit();

  const handleCompileReport = () => {
    // Save state to localStorage to trigger the Vendor Auditor badge on Progress Tracker!
    localStorage.setItem("cu_ai_vendor_audited", "true");
    window.dispatchEvent(new Event("progressUpdated"));
    setShowBrief(true);
  };

  return (
    <div className="section" style={{ paddingTop: "40px" }}>
      <div className="container">
        
        {/* Breadcrumb */}
        <Link 
          href="/" 
          style={{ 
            display: "inline-flex", 
            alignItems: "center", 
            gap: "8px", 
            color: "var(--text-secondary)", 
            textDecoration: "none",
            marginBottom: "24px",
            fontSize: "0.9rem",
            fontWeight: 500,
          }}
          className="nav-link"
        >
          <ArrowLeft style={{ width: 16, height: 16 }} />
          <span>Back to Dashboard</span>
        </Link>

        {/* Title */}
        <div style={{ marginBottom: "30px" }}>
          <span className="badge badge-board" style={{ marginBottom: "10px" }}>Governance Tool</span>
          <h1 className="gradient-text" style={{ fontSize: "2.25rem", marginBottom: "8px" }}>
            AI Vendor Governance Auditor
          </h1>
          <p style={{ color: "var(--text-secondary)", maxWidth: "850px" }}>
            Perform vendor risk management checks under NCUA Letters to Credit Unions and GLBA privacy requirements. Evaluate third-party SaaS contracts, compute compliance grades, and download board briefing sheets.
          </p>
        </div>

        {/* Auditor Form Layout */}
        <div style={{ display: "grid", gridTemplateColumns: "1.2.fr 0.8fr", gap: "24px", alignItems: "start" }} className="auditor-grid">
          
          {/* Questions Checkbox Column */}
          <div className="card" style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
            
            {/* Vendor Title Input */}
            <div className="form-group" style={{ borderBottom: "1px solid var(--border-color)", paddingBottom: "20px", marginBottom: "0" }}>
              <label className="form-label">Vendor Company Name</label>
              <input 
                type="text" 
                className="form-input" 
                value={vendorName}
                onChange={(e) => { setVendorName(e.target.value); setShowBrief(false); }}
                placeholder="e.g. UnderwriteAI Corp"
                style={{ maxWidth: "400px" }}
              />
            </div>

            {/* Checklist */}
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              {auditQuestions.map((q) => (
                <label
                  key={q.id}
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "14px",
                    padding: "16px",
                    borderRadius: "var(--radius-md)",
                    border: "1px solid var(--border-color)",
                    backgroundColor: selectedAnswers[q.id] ? "rgba(16, 185, 129, 0.03)" : "rgba(255,255,255,0.01)",
                    cursor: "pointer",
                    transition: "all 0.2s ease"
                  }}
                >
                  <input
                    type="checkbox"
                    checked={selectedAnswers[q.id]}
                    onChange={() => toggleAnswer(q.id)}
                    style={{ width: "20px", height: "20px", marginTop: "2px", accentColor: "var(--success)", cursor: "pointer" }}
                  />
                  
                  <div style={{ flex: 1 }}>
                    <div style={{ display: "flex", gap: "8px", alignItems: "center", marginBottom: "4px" }}>
                      <span className="badge badge-staff" style={{ fontSize: "0.6rem", padding: "1px 6px" }}>{q.category}</span>
                      <span style={{ fontSize: "0.75rem", color: "var(--text-muted)", fontWeight: "bold" }}>+{q.points} Points</span>
                    </div>
                    <span style={{ fontSize: "0.95rem", color: "var(--text-primary)", fontWeight: 600, display: "block" }}>
                      {q.question}
                    </span>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {/* Results Side Box */}
          <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
            
            {/* Grade card */}
            <div className="card text-center" style={{ padding: "30px", border: "1px solid var(--border-color)", textAlign: "center" }}>
              <Shield className="gradient-text-indigo" style={{ width: 44, height: 44, margin: "0 auto 12px auto" }} />
              <h3 style={{ fontSize: "1.2rem", marginBottom: "6px" }}>Vendor Security Grade</h3>
              <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginBottom: "20px" }}>
                Fiduciary compliance evaluation score.
              </p>

              {/* Visual Alphabet Grade */}
              <div 
                style={{ 
                  width: "120px", 
                  height: "120px", 
                  borderRadius: "50%", 
                  border: `6px solid ${report.color}`,
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  margin: "0 auto 20px auto",
                  backgroundColor: "rgba(255, 255, 255, 0.02)",
                  boxShadow: `0 0 25px ${report.color}1b`
                }}
              >
                <span style={{ fontSize: "3rem", fontWeight: 800, color: report.color, lineHeight: 1 }}>
                  {report.grade}
                </span>
                <span style={{ fontSize: "0.75rem", color: "var(--text-secondary)", fontWeight: 700, marginTop: "2px" }}>
                  {report.scorePercentage}% Compliance
                </span>
              </div>

              {/* Status Banner */}
              <div 
                style={{ 
                  padding: "10px", 
                  borderRadius: "var(--radius-md)", 
                  backgroundColor: report.bg, 
                  color: report.color, 
                  fontWeight: 700,
                  fontSize: "1rem",
                  border: `1px solid ${report.color}33`,
                  marginBottom: "20px"
                }}
              >
                {report.riskLevel} Rating
              </div>

              {/* Compile Report Button */}
              <button 
                onClick={handleCompileReport} 
                className="btn btn-primary"
                style={{ width: "100%" }}
              >
                <FileText style={{ width: 16, height: 16 }} />
                <span>Compile Briefing Sheet</span>
              </button>
            </div>

            {/* Board Reference Info Box */}
            <div className="card" style={{ padding: "20px" }}>
              <div style={{ display: "flex", gap: "8px", alignItems: "center", marginBottom: "10px", color: "var(--warning)" }}>
                <ShieldAlert style={{ width: 18, height: 18 }} />
                <h4 style={{ fontSize: "0.95rem", margin: 0, fontWeight: 700 }}>Fiduciary Compliance Note</h4>
              </div>
              <p style={{ fontSize: "0.8rem", color: "var(--text-secondary)", lineHeight: 1.5 }}>
                Regulatory audits by the <strong>NCUA</strong> examine third-party SaaS technology platforms. Fiduciary duties prevent boards from signing contracts that grant vendor ownership of member database inputs or waive intellectual property lawsuit shields.
              </p>
            </div>
          </div>
        </div>

        {/* Board Briefing Sheet */}
        {showBrief && (
          <div 
            id="printable-auditor-report"
            className="card animate-fade-in-up"
            style={{ 
              marginTop: "40px", 
              padding: "40px", 
              border: "1px solid var(--border-color)",
              backgroundColor: "#0d0f22"
            }}
          >
            {showPDFTip && (
              <div 
                className="animate-fade-in"
                style={{ 
                  padding: "14px 20px", 
                  borderRadius: "var(--radius-md)", 
                  backgroundColor: "rgba(99, 102, 241, 0.1)", 
                  border: "1px solid var(--primary)", 
                  color: "var(--text-primary)",
                  fontSize: "0.85rem",
                  marginBottom: "20px",
                  display: "flex",
                  alignItems: "center",
                  gap: "10px"
                }}
              >
                <Info style={{ width: 18, height: 18, color: "var(--primary)" }} />
                <span>
                  <strong>Tip:</strong> In the browser print window that opens, change the <strong>Destination</strong> to <strong>Save as PDF</strong> (or Microsoft Print to PDF) to download this compliance report.
                </span>
              </div>
            )}

            <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "2px solid var(--border-color)", paddingBottom: "20px", marginBottom: "30px", flexWrap: "wrap", gap: "20px" }}>
              <div>
                <h2 style={{ fontSize: "1.75rem", marginBottom: "4px" }} className="gradient-text">
                  AI Vendor Diligence Checklist
                </h2>
                <p style={{ fontSize: "0.9rem", color: "var(--text-secondary)" }}>
                  Oversight Briefing: <strong>{vendorName}</strong>
                </p>
              </div>
              
              <div style={{ display: "flex", gap: "10px", alignSelf: "center" }}>
                <button 
                  onClick={handleExportPDF} 
                  className="btn btn-primary"
                  style={{ display: "flex", alignItems: "center", gap: "6px" }}
                >
                  <Download style={{ width: 16, height: 16 }} />
                  <span>Export PDF</span>
                </button>
                <button 
                  onClick={() => window.print()} 
                  className="btn btn-secondary"
                  style={{ display: "flex", alignItems: "center", gap: "6px" }}
                >
                  <Printer style={{ width: 16, height: 16 }} />
                  <span>Print</span>
                </button>
              </div>
            </div>

            {/* Report Content Grid */}
            <div style={{ display: "grid", gridTemplateColumns: "1.2fr 0.8fr", gap: "40px" }} className="briefing-grid">
              
              {/* Audit Questions to Ask */}
              <div>
                <h3 style={{ fontSize: "1.2rem", marginBottom: "16px", color: "var(--text-primary)" }}>
                  Negotiation Audit Questions
                </h3>
                <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginBottom: "20px", lineHeight: 1.5 }}>
                  Based on unchecked scorecard items, management should request clarifications on these topics from <strong>{vendorName}</strong> representatives:
                </p>

                {report.gaps.length === 0 ? (
                  <div style={{ padding: "16px", borderRadius: "var(--radius-md)", backgroundColor: "var(--success-glow)", border: "1px solid var(--success)", color: "var(--success)", fontSize: "0.85rem" }}>
                    <strong>All Criteria Met:</strong> No critical gaps found in SaaS security, fairness, or legal contracts.
                  </div>
                ) : (
                  <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                    {report.gaps.map((gap) => (
                      <div 
                        key={gap.id}
                        style={{
                          padding: "16px",
                          borderRadius: "var(--radius-md)",
                          backgroundColor: "rgba(255,255,255,0.02)",
                          border: "1px solid var(--border-color)"
                        }}
                      >
                        <strong style={{ fontSize: "0.85rem", color: "var(--warning)", display: "flex", alignItems: "center", gap: "6px", marginBottom: "6px" }}>
                          <AlertTriangle style={{ width: 14, height: 14 }} />
                          {gap.category} Requirement Gap
                        </strong>
                        <p style={{ fontSize: "0.8rem", color: "var(--text-secondary)", marginBottom: "8px", lineHeight: 1.4 }}>
                          {gap.gapText}
                        </p>
                        <div style={{ padding: "10px", borderRadius: "var(--radius-sm)", backgroundColor: "rgba(99,102,241,0.04)", borderLeft: "3px solid var(--primary)", fontSize: "0.75rem", fontFamily: "monospace", color: "var(--text-secondary)" }}>
                          <strong>Ask:</strong> &quot;{gap.vendorQuestion}&quot;
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Summary and Gaps */}
              <div 
                style={{ 
                  padding: "24px", 
                  borderRadius: "var(--radius-md)", 
                  backgroundColor: "rgba(255,255,255,0.02)",
                  border: "1px solid var(--border-color)",
                  alignSelf: "start"
                }}
              >
                <h3 style={{ fontSize: "1.05rem", marginBottom: "16px", color: "var(--text-primary)" }}>
                  Governance Record
                </h3>
                
                <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid rgba(255,255,255,0.04)", paddingBottom: "8px", fontSize: "0.85rem" }}>
                    <span style={{ color: "var(--text-secondary)" }}>Grade:</span>
                    <strong style={{ color: report.color }}>{report.grade}</strong>
                  </div>
                  <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid rgba(255,255,255,0.04)", paddingBottom: "8px", fontSize: "0.85rem" }}>
                    <span style={{ color: "var(--text-secondary)" }}>Risk Status:</span>
                    <strong style={{ color: report.color }}>{report.riskLevel}</strong>
                  </div>
                  <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid rgba(255,255,255,0.04)", paddingBottom: "8px", fontSize: "0.85rem" }}>
                    <span style={{ color: "var(--text-secondary)" }}>Score:</span>
                    <strong style={{ color: "var(--text-primary)" }}>{report.scorePercentage}% Compliance</strong>
                  </div>
                  <div style={{ display: "flex", justifyContent: "space-between", paddingBottom: "8px", fontSize: "0.85rem" }}>
                    <span style={{ color: "var(--text-secondary)" }}>Oversight Status:</span>
                    <span className="badge badge-mgmt" style={{ fontSize: "0.65rem" }}>BOARD REVIEW READY</span>
                  </div>
                </div>

                {report.scorePercentage < 75 && (
                  <div 
                    style={{ 
                      padding: "12px", 
                      borderRadius: "var(--radius-sm)", 
                      backgroundColor: "rgba(239, 68, 68, 0.05)", 
                      border: "1px solid var(--danger)", 
                      color: "var(--danger)",
                      fontSize: "0.75rem",
                      lineHeight: 1.4,
                      marginTop: "20px"
                    }}
                  >
                    <strong>ALERT:</strong> This vendor scorecard is below the credit union compliance limit of 75%. Management must negotiate contract updates or resolve the information security/data isolation gaps before routing for board signing.
                  </div>
                )}
              </div>

            </div>
          </div>
        )}

      </div>
      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
            background: #ffffff !important;
            color: #000000 !important;
          }
          #printable-auditor-report, #printable-auditor-report * {
            visibility: visible;
          }
          #printable-auditor-report {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            border: none !important;
            background: #ffffff !important;
            color: #000000 !important;
            padding: 0 !important;
          }
          .gradient-text, .gradient-text-indigo {
            background: none !important;
            -webkit-text-fill-color: initial !important;
            color: #000000 !important;
          }
          button {
            display: none !important;
          }
        }
        @media (max-width: 900px) {
          .auditor-grid, .briefing-grid {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </div>
  );
}
