"use client";

import React, { useState } from "react";
import { 
  ShieldAlert, ShieldCheck, Play, Pause, RefreshCw, 
  Video, Mail, AlertTriangle, CheckCircle, ArrowRight
} from "lucide-react";

interface Choice {
  text: string;
  isCorrect: boolean;
  feedback: string;
}

interface Scenario {
  id: number;
  title: string;
  type: "voice" | "video" | "email";
  description: string;
  instruction: string;
  choices: Choice[];
}

const scenarios: Scenario[] = [
  {
    id: 1,
    title: "Scenario 1: Executive Voice Clone (Vishing)",
    type: "voice",
    description: "You receive an incoming call from 'CEO Robert'. His voice sounds urgent and perfectly recognizable.",
    instruction: "Choose the action that maintains security and complies with data safety rules:",
    choices: [
      {
        text: "Process the transfer bypass immediately to avoid delaying the CEO.",
        isCorrect: false,
        feedback: "Security compromised! The voice was an AI clone trained on a 3-second sample of Robert's public speeches. By bypassing the hold, you transferred $25,000 straight to a fraudster's account."
      },
      {
        text: "Trust the call but ask the CEO to email you a formal request first.",
        isCorrect: false,
        feedback: "Vulnerable protocol! The attacker has a pre-written template and uses AI text tools to send a spoofed email instantly. You still approved a transaction without verifying the caller out-of-band."
      },
      {
        text: "Politely decline, hang up, and call the CEO back on their registered corporate number.",
        isCorrect: true,
        feedback: "Excellent work! This is a textbook defense. AI voice clones can be highly realistic, but they cannot intercept an out-of-band callback made directly to the CEO's official phone number."
      }
    ]
  },
  {
    id: 2,
    title: "Scenario 2: Video Meeting (Deepfake Video)",
    type: "video",
    description: "During a Microsoft Teams call, 'Sarah from NCUA' requests a database screenshare. Her feed has slight blurring around her hair and jawline.",
    instruction: "Select the most effective real-time behavioral check to verify her feed:",
    choices: [
      {
        text: "Trust Sarah's credentials and proceed to share the database layout.",
        isCorrect: false,
        feedback: "Data Leak! The video was a real-time deepfake mask. Attackers used this screenshare to map the credit union's internal database structure and orchestrate SQL injections."
      },
      {
        text: "Ask Sarah to turn her head 90 degrees sideways to inspect the profile rendering.",
        isCorrect: true,
        feedback: "Brilliant check! Real-time deepfake mapping models rely on frontal facial grids. When forced to turn 90 degrees (showing a lateral profile), the synthesis fails, creating obvious edge warping, blurring, and visual glitching."
      },
      {
        text: "Ask Sarah to email you her official government badge for confirmation.",
        isCorrect: false,
        feedback: "Insufficient check! Badges and IDs can easily be photoshopped or generated by AI in seconds. In a live session, behavioral checks or out-of-band trust tokens are required."
      }
    ]
  },
  {
    id: 3,
    title: "Scenario 3: Hyper-Targeted AI Phishing",
    type: "email",
    description: "You receive an email referencing your recent LinkedIn post about Credit Union security upgrades. It requests a review of 'loan_audit_guide.zip'.",
    instruction: "Analyze the email and decide how to respond:",
    choices: [
      {
        text: "Download and open the zip file since it references your actual LinkedIn post.",
        isCorrect: false,
        feedback: "Infection! Threat actors use AI to scrape public social footprints and write custom phishing. The zip file contained a credential harvester that compromised your network."
      },
      {
        text: "Flag the email as suspicious, check the sender domain, and report it to IT Security.",
        isCorrect: true,
        feedback: "Perfect! You noticed that the sender's domain (secure-creditunion-ncua.org) was spoofed to mimic NCUA (ncua.gov). Reporting to IT blocks the attack vector for the entire organization."
      },
      {
        text: "Reply to the sender asking if the file is safe to open.",
        isCorrect: false,
        feedback: "Trap triggered! The attacker's AI bot is automated to reply immediately with a professional message assuring you it is safe, leading you to download the file."
      }
    ]
  }
];

export default function ThreatSimulator() {
  const [activeStep, setActiveStep] = useState(0);
  const [selectedChoice, setSelectedChoice] = useState<number | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [showFinalResults, setShowFinalResults] = useState(false);
  const [isFaceGlitching, setIsFaceGlitching] = useState(false);
  const [emailRedFlags, setEmailRedFlags] = useState(false);

  const scenario = scenarios[activeStep];

  const handleChoiceSelect = (idx: number) => {
    if (isSubmitted) return;
    setSelectedChoice(idx);
  };

  const handleSubmit = () => {
    if (selectedChoice === null) return;
    setIsSubmitted(true);
    const correct = scenario.choices[selectedChoice].isCorrect;
    if (correct) {
      setScore(prev => prev + 1);
    }
  };

  const handleNext = () => {
    setSelectedChoice(null);
    setIsSubmitted(false);
    setIsPlayingAudio(false);
    setIsFaceGlitching(false);
    setEmailRedFlags(false);

    if (activeStep < scenarios.length - 1) {
      setActiveStep(prev => prev + 1);
    } else {
      setShowFinalResults(true);
      // Trigger event to refresh global progress
      localStorage.setItem("cu_ai_progress_infosec", "completed");
      localStorage.setItem("cu_ai_score_infosec", "100");
      window.dispatchEvent(new Event("progressUpdated"));
    }
  };

  const handleRestart = () => {
    setActiveStep(0);
    setSelectedChoice(null);
    setIsSubmitted(false);
    setScore(0);
    setShowFinalResults(false);
    setIsPlayingAudio(false);
    setIsFaceGlitching(false);
    setEmailRedFlags(false);
  };

  if (showFinalResults) {
    const passed = score === scenarios.length;
    return (
      <div className="card text-center animate-fade-in-up" style={{ padding: "40px 24px", maxWidth: "600px", margin: "20px auto" }}>
        <div 
          style={{
            width: "70px",
            height: "70px",
            borderRadius: "50%",
            background: passed ? "var(--success-glow)" : "var(--danger-glow)",
            color: passed ? "var(--success)" : "var(--danger)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            margin: "0 auto 20px auto"
          }}
        >
          {passed ? <ShieldCheck style={{ width: 36, height: 36 }} /> : <ShieldAlert style={{ width: 36, height: 36 }} />}
        </div>
        <h3 className="gradient-text" style={{ fontSize: "1.75rem", marginBottom: "12px" }}>
          {passed ? "Zero-Trust Certification Completed!" : "Simulator Finished"}
        </h3>
        <p style={{ color: "var(--text-secondary)", marginBottom: "20px", fontSize: "0.95rem" }}>
          {passed 
            ? "Congratulations! You correctly identified all AI social engineering threats and implemented zero-trust defenses." 
            : `You answered ${score} of ${scenarios.length} scenarios correctly. Retake the simulator to achieve a perfect score.`
          }
        </p>
        <div style={{ fontSize: "3rem", fontWeight: 800, color: passed ? "var(--success)" : "var(--warning)", marginBottom: "24px" }}>
          {score} / {scenarios.length}
        </div>
        <button onClick={handleRestart} className="btn btn-secondary">
          <RefreshCw style={{ width: 16, height: 16 }} />
          <span>Restart Simulator</span>
        </button>
      </div>
    );
  }

  return (
    <div className="card animate-fade-in-up" style={{ padding: "30px", maxWidth: "700px", margin: "20px auto", border: "1px solid var(--border-color)" }}>
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px", borderBottom: "1px solid var(--border-color)", paddingBottom: "14px" }}>
        <span style={{ display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "0.85rem", textTransform: "uppercase", fontWeight: 700, color: "var(--danger)" }}>
          <ShieldAlert style={{ width: 16, height: 16 }} />
          AI Threat Simulation Lab
        </span>
        <span style={{ fontSize: "0.85rem", color: "var(--text-secondary)" }}>
          Scenario <strong>{activeStep + 1}</strong> of {scenarios.length}
        </span>
      </div>

      <h3 style={{ fontSize: "1.35rem", marginBottom: "12px" }}>{scenario.title}</h3>
      <p style={{ color: "var(--text-secondary)", fontSize: "0.95rem", marginBottom: "24px", lineHeight: 1.5 }}>
        {scenario.description}
      </p>

      {/* Interactive Interface Elements based on Type */}
      <div style={{ marginBottom: "30px" }}>
        {scenario.type === "voice" && (
          <div 
            style={{ 
              background: "rgba(6, 8, 20, 0.4)", 
              border: "1px solid var(--border-color)", 
              borderRadius: "var(--radius-md)", 
              padding: "20px",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "16px"
            }}
          >
            {/* Cloned Audio Player */}
            <div style={{ display: "flex", alignItems: "center", gap: "12px", width: "100%" }}>
              <button 
                onClick={() => setIsPlayingAudio(!isPlayingAudio)}
                style={{ 
                  background: isPlayingAudio ? "var(--danger)" : "var(--primary)", 
                  border: "none", 
                  borderRadius: "50%", 
                  width: "48px", 
                  height: "48px", 
                  display: "flex", 
                  alignItems: "center", 
                  justifyContent: "center", 
                  cursor: "pointer",
                  color: "#fff"
                }}
              >
                {isPlayingAudio ? <Pause style={{ width: 20, height: 20 }} /> : <Play style={{ width: 20, height: 20 }} />}
              </button>
              
              <div style={{ flex: 1 }}>
                <p style={{ fontSize: "0.8rem", color: "var(--text-muted)", marginBottom: "4px" }}>Incoming Encrypted Voice Link</p>
                <div style={{ display: "flex", alignItems: "center", gap: "3px", height: "24px" }}>
                  {/* Waveform Animation */}
                  {Array.from({ length: 28 }).map((_, i) => (
                    <div 
                      key={i} 
                      style={{ 
                        flex: 1, 
                        background: isPlayingAudio ? "var(--danger)" : "var(--text-muted)", 
                        height: isPlayingAudio ? `${Math.sin(i * 0.5) * 10 + 14}px` : "4px",
                        animation: isPlayingAudio ? `wave 1.2s ease-in-out infinite alternate` : "none",
                        animationDelay: `${i * 0.04}s`,
                        borderRadius: "2px",
                        transition: "all 0.2s"
                      }}
                    />
                  ))}
                </div>
              </div>
            </div>

            <div 
              style={{ 
                fontStyle: "italic", 
                color: isPlayingAudio ? "var(--text-primary)" : "var(--text-muted)", 
                fontSize: "0.9rem", 
                backgroundColor: "rgba(255, 255, 255, 0.02)", 
                padding: "12px", 
                borderRadius: "var(--radius-sm)", 
                borderLeft: "3px solid var(--danger)",
                width: "100%",
                lineHeight: 1.5
              }}
            >
              &ldquo;Emergency! This is Robert. The database servers are down and I need you to bypass the wire check limit for Member A&apos;s transfer of $25,000 immediately. I&apos;m boarding a flight in 2 minutes so do it now!&rdquo;
            </div>
          </div>
        )}

        {scenario.type === "video" && (
          <div 
            style={{ 
              background: "rgba(6, 8, 20, 0.5)", 
              border: "1px solid var(--border-color)", 
              borderRadius: "var(--radius-md)", 
              overflow: "hidden",
              position: "relative",
              aspectRatio: "16 / 9",
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between"
            }}
          >
            {/* Simulated Video Feed */}
            <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyItems: "center", justifyContent: "center", background: "#0c0e1b" }}>
              <div 
                style={{ 
                  textAlign: "center", 
                  color: "var(--text-secondary)",
                  filter: isFaceGlitching ? "blur(1px) contrast(150%)" : "none",
                  transition: "all 0.1s"
                }}
              >
                <Video style={{ width: 64, height: 64, margin: "0 auto 12px auto", color: "var(--accent)", opacity: 0.8 }} />
                <p style={{ fontSize: "1.1rem", color: "var(--text-primary)", fontWeight: 600 }}>Sarah Jenkins (NCUA Auditor)</p>
                <p style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>Secure Video Call Feed</p>
                {isFaceGlitching && (
                  <div style={{ position: "absolute", top: "20px", left: "50%", transform: "translateX(-50%)", background: "var(--danger)", padding: "4px 8px", borderRadius: "4px", fontSize: "0.7rem", color: "white", fontWeight: 700 }}>
                    ⚠️ SYNTHESIS EDGE DISTORTION DETECTED
                  </div>
                )}
              </div>
            </div>

            {/* Video overlay badges */}
            <div style={{ zIndex: 2, padding: "12px", display: "flex", justifyContent: "space-between", width: "100%" }}>
              <span className="badge badge-staff" style={{ background: "rgba(6, 182, 212, 0.4)", textTransform: "none" }}>Live Webcam</span>
              <span style={{ fontSize: "0.8rem", background: "rgba(0,0,0,0.6)", padding: "2px 8px", borderRadius: "4px" }}>1080p Stream</span>
            </div>

            {/* Action check button */}
            <div style={{ zIndex: 2, padding: "12px", width: "100%", display: "flex", justifyContent: "flex-end" }}>
              <button 
                onClick={() => {
                  setIsFaceGlitching(true);
                  setTimeout(() => setIsFaceGlitching(false), 2000);
                }}
                className="btn btn-secondary" 
                style={{ padding: "6px 12px", fontSize: "0.75rem", display: "flex", alignItems: "center", gap: "6px" }}
              >
                <RefreshCw style={{ width: 12, height: 12 }} />
                <span>Test Profile Angle (Motion Challenge)</span>
              </button>
            </div>
          </div>
        )}

        {scenario.type === "email" && (
          <div 
            style={{ 
              background: "#0c0e1b", 
              border: "1px solid var(--border-color)", 
              borderRadius: "var(--radius-md)", 
              padding: "16px",
              display: "flex",
              flexDirection: "column",
              gap: "12px"
            }}
          >
            {/* Simulated Email */}
            <div style={{ borderBottom: "1px solid var(--border-color)", paddingBottom: "10px", fontSize: "0.85rem" }}>
              <p style={{ margin: "2px 0" }}><strong style={{ color: "var(--text-secondary)" }}>From:</strong> Sarah Jenkins <span style={{ color: emailRedFlags ? "var(--danger)" : "var(--text-muted)", fontWeight: emailRedFlags ? 700 : 500 }}>&lt;s.jenkins@secure-creditunion-ncua.org&gt;</span></p>
              <p style={{ margin: "2px 0" }}><strong style={{ color: "var(--text-secondary)" }}>To:</strong> Branch Staff Member</p>
              <p style={{ margin: "2px 0" }}><strong style={{ color: "var(--text-secondary)" }}>Subject:</strong> <span style={{ fontWeight: 600 }}>URGENT: Review of your Q2 loan policy submission</span></p>
            </div>
            
            <div style={{ fontSize: "0.9rem", color: "var(--text-primary)", lineHeight: 1.5 }}>
              <p style={{ marginBottom: "10px" }}>Hi there,</p>
              <p style={{ marginBottom: "10px" }}>
                I saw your LinkedIn post about completing the Credit Union AI Audit project. Excellent job! 
                {emailRedFlags && <span style={{ background: "rgba(245, 158, 11, 0.25)", color: "var(--warning)", padding: "2px", border: "1px dashed var(--warning)" }}> [Red Flag: AI-scraped public profile bait]</span>}
              </p>
              <p style={{ marginBottom: "10px" }}>
                We need to verify your Q2 loan guidelines immediately. Please download and run the following encrypted verification script file to submit audit checks:
              </p>
              <div 
                style={{ 
                  display: "inline-flex", 
                  alignItems: "center", 
                  gap: "8px", 
                  padding: "8px 12px", 
                  borderRadius: "var(--radius-sm)", 
                  background: "rgba(255, 255, 255, 0.03)", 
                  border: emailRedFlags ? "1px solid var(--danger)" : "1px solid var(--border-color)"
                }}
              >
                <Mail style={{ width: 16, height: 16, color: "var(--danger)" }} />
                <span style={{ fontSize: "0.8rem", color: emailRedFlags ? "var(--danger)" : "var(--text-primary)", fontWeight: 500 }}>loan_audit_guide.zip</span>
              </div>
            </div>

            <div style={{ display: "flex", justifyContent: "flex-end" }}>
              <button 
                onClick={() => setEmailRedFlags(!emailRedFlags)}
                className="btn btn-outline" 
                style={{ padding: "6px 12px", fontSize: "0.75rem" }}
              >
                <span>{emailRedFlags ? "Hide Highlighted Hooks" : "Scan for Social Engineering Hooks"}</span>
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Choices section */}
      <div style={{ display: "flex", flexDirection: "column", gap: "12px", marginBottom: "24px" }}>
        <p style={{ fontSize: "0.9rem", fontWeight: 600, color: "var(--text-primary)" }}>{scenario.instruction}</p>
        
        {scenario.choices.map((choice, idx) => {
          const isSelected = selectedChoice === idx;
          const choiceStyle: React.CSSProperties = {
            padding: "14px 16px",
            borderRadius: "var(--radius-md)",
            border: "1px solid var(--border-color)",
            background: "rgba(255, 255, 255, 0.02)",
            textAlign: "left",
            cursor: isSubmitted ? "not-allowed" : "pointer",
            fontSize: "0.9rem",
            color: "var(--text-primary)",
            transition: "all 0.2s",
            display: "flex",
            alignItems: "flex-start",
            gap: "10px"
          };

          if (!isSubmitted) {
            if (isSelected) {
              choiceStyle.borderColor = "var(--primary)";
              choiceStyle.background = "var(--primary-glow)";
            }
          } else {
            if (choice.isCorrect) {
              choiceStyle.borderColor = "var(--success)";
              choiceStyle.background = "var(--success-glow)";
            } else if (isSelected) {
              choiceStyle.borderColor = "var(--danger)";
              choiceStyle.background = "var(--danger-glow)";
            } else {
              choiceStyle.opacity = 0.4;
            }
          }

          return (
            <button 
              key={idx}
              disabled={isSubmitted}
              onClick={() => handleChoiceSelect(idx)}
              style={choiceStyle}
              className={`choice-button ${!isSubmitted ? "choice-hoverable" : ""}`}
            >
              <div 
                style={{ 
                  width: "18px", 
                  height: "18px", 
                  borderRadius: "50%", 
                  border: `2px solid ${isSelected ? "var(--primary)" : "var(--text-muted)"}`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                  marginTop: "2px"
                }}
              >
                {isSelected && <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--primary)" }} />}
              </div>
              <span>{choice.text}</span>
            </button>
          );
        })}
      </div>

      {/* Submit/Next Actions */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div>
          {isSubmitted && (
            <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
              {scenario.choices[selectedChoice!].isCorrect ? (
                <span style={{ color: "var(--success)", fontSize: "0.9rem", fontWeight: 700, display: "flex", alignItems: "center", gap: "4px" }}>
                  <CheckCircle style={{ width: 16, height: 16 }} /> Correct Selection
                </span>
              ) : (
                <span style={{ color: "var(--danger)", fontSize: "0.9rem", fontWeight: 700, display: "flex", alignItems: "center", gap: "4px" }}>
                  <AlertTriangle style={{ width: 16, height: 16 }} /> Attack Vector Triggered
                </span>
              )}
            </div>
          )}
        </div>

        <div>
          {!isSubmitted ? (
            <button 
              onClick={handleSubmit} 
              disabled={selectedChoice === null}
              className="btn btn-primary"
              style={{ opacity: selectedChoice === null ? 0.5 : 1 }}
            >
              <span>Submit Assessment</span>
            </button>
          ) : (
            <button onClick={handleNext} className="btn btn-accent">
              <span>{activeStep < scenarios.length - 1 ? "Next Scenario" : "View Final Results"}</span>
              <ArrowRight style={{ width: 16, height: 16 }} />
            </button>
          )}
        </div>
      </div>

      {/* Explanations Details */}
      {isSubmitted && (
        <div 
          className="animate-fade-in-up"
          style={{ 
            marginTop: "20px", 
            padding: "16px", 
            borderRadius: "var(--radius-md)", 
            backgroundColor: "rgba(255, 255, 255, 0.02)",
            borderLeft: `4px solid ${scenario.choices[selectedChoice!].isCorrect ? "var(--success)" : "var(--danger)"}`,
            fontSize: "0.9rem",
            color: "var(--text-secondary)",
            lineHeight: 1.5
          }}
        >
          <strong style={{ color: "var(--text-primary)", display: "block", marginBottom: "4px" }}>Analysis:</strong>
          {scenario.choices[selectedChoice!].feedback}
        </div>
      )}

      {/* Wave animation CSS */}
      <style jsx>{`
        @keyframes wave {
          0% { transform: scaleY(0.3); }
          100% { transform: scaleY(1.4); }
        }
        .choice-hoverable:hover {
          background-color: rgba(255, 255, 255, 0.05) !important;
          border-color: rgba(255, 255, 255, 0.15) !important;
          transform: translateX(2px);
        }
      `}</style>
    </div>
  );
}
